# Generated by Django 4.1.7 on 2024-04-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataextractor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="source",
            field=models.TextField(blank=True, default="FB", null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="source",
            field=models.TextField(blank=True, default="FB", null=True),
        ),
    ]
